field: 1aa3f56d-0e79-4a95-abd0-a84bd0983e97 # Business socials
fieldLayouts:
  a10b5846-9714-4fe8-888b-bbf220061cd9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8f4f5840-da22-468a-b487-8bf4e6c6f4e8 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc9fa158-cca2-4b6f-a5ea-00ba2514fdaa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 769af350-7abf-4f94-9080-ae23cfb9288a # Social media type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b7d6303-42ef-4c05-9099-6d6f345ad7b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17102bb1-be3e-45a3-bc49-0a72ac287a9f
        userCondition: null
fields:
  8f4f5840-da22-468a-b487-8bf4e6c6f4e8: # Link
    columnSuffix: yganbmfx
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkTo
    instructions: null
    name: Link
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  769af350-7abf-4f94-9080-ae23cfb9288a: # Social media type
    columnSuffix: lqctatlj
    contentColumnType: string(9)
    fieldGroup: null
    handle: socialMediaType
    instructions: null
    name: 'Social media type'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Facebook
            -
              - value
              - facebook
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Instagram
            -
              - value
              - instagram
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Linkedin
            -
              - value
              - linkedin
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: social
name: Social
sortOrder: 1
