columnSuffix: sbvzxcgj
contentColumnType: text
fieldGroup: bf273aa4-de6e-4791-8ca5-57f2616fe1f8 # Common
handle: businessPhoneNumber
instructions: null
name: 'Business phone number'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
